---
title: "Exploration of the Home Credit Dataset"
output:
  html_notebook:
    toc: yes
    toc_float: true
---

```{r, echo=FALSE, warning=FALSE}
library(data.table)
library(skimr)
library(ggplot2)

# Load data -----
# Note: here we assume that the data extraction and integration is
# already done.
dev <- fread('data/application_train.csv', stringsAsFactors = FALSE)
names(dev) <- tolower(names(dev))
descr <- fread('data/HomeCredit_columns_description.csv', stringsAsFactors = FALSE)
descr <- descr[Table == 'application_{train|test}.csv', ]

# Data exploration
skim_dev <- data.table(skim(dev))

```

## Character Variables
Practically the empty fields and the XNA values are the missing ones so we convert these values to missing.
```{r, echo=FALSE, warning=FALSE}
# Quickly explore character variables ----
cols <- unique(skim_dev[skim_dev$type == 'character']$variable)
skim_dev_chr <- data.table()
for(i in cols){
  r <- dev[, .(.N), by = i]
  names(r)[1] <- "value"
  r$var <- i
  skim_dev_chr <- rbind(skim_dev_chr, r[,.(var, value, N)])
}
# Practically the empty fields and the XNA values are the missing ones
# so we convert these values to missing
dev[, (cols) := lapply(.SD, function(x) ifelse(x %in% c('','XNA'), NA, x))
      , .SDcols = cols]
skim(dev[, cols, with=FALSE])
rm('r', 'cols') # cleanup

```

## Flags
We recode the flag\_own\_car and flag\_own\_reality from Yes:No to 1:0.
```{r, echo=FALSE, warning=FALSE}
# Recode the flag_own_car and flag_own_reality to 0/1
dev$flag_own_car <- ifelse(dev$flag_own_car == 'N', as.integer(0), as.integer(1))
dev$flag_own_realty <- ifelse(dev$flag_own_realty == 'N', as.integer(0), as.integer(1))
# Some of them are flags while others are counters
# Let's identify first the flag variables using the metatdata descr
cols <- tolower(descr[substr(Row,1,4) == 'FLAG' | substr(Description,1,4) == 'Flag', ]$Row)
skim(dev[, (cols), with=F])
rm('cols')
```

## Numeric Variables
We drop all those numeric input factors where the missing ratio is above 30\%.

```{r, echo=FALSE, warning=FALSE}
# Quickly explore numeric variables ----
# Our general rule is that if the missing ratio is above 30%
# then we drop the variable
skim_dev_num <- skim_dev[type == 'numeric' & stat %in% c('missing','n'), .(variable, stat, value)]
skim_dev_num <- dcast(skim_dev_num, variable ~ stat)
skim_dev_num[, rat_missing := missing/n]

```

